site_name: Informations Systems Exercises
repo_url: https://github.com/TGM-HIT/insy-exercises

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

edit_uri: "edit/main/docs/"
